package com.company;





public class Main  {

    public static void main(String[] args) {

        System.out.println("Hello this Program is for Bubble Sort in Java .");
        System.out.println("Here elements will be generated by users  .");



        System.out.println("lets start");
        BubbleSort obj=new BubbleSort();
        obj.typesofArray();
    }



}
