package com.company;


import java.util.Scanner;

public class Main {


    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        RandomArray obj2 = new RandomArray();
        UserArray obj3 = new UserArray();
        int ch;
        boolean t = true;

        System.out.println("Hello this Program is for Bubble Sort in Java .");
        System.out.println("Here elements will be generated by users  .");


        System.out.println("lets start");


        while (t) {
            System.out.println("Please enter the choice of Sorting");
            System.out.println("Press 1 for Integer type Sorting");
            System.out.println("Press 2 for Character type Sorting");
            System.out.println("Press 3 for long type Sorting");
            System.out.println("Press 4 for boolean type Sorting");
            System.out.println("Press 5 for String type Sorting");
            System.out.println("Press 6 to exit");

            int choice = sc.nextInt();
            switch (choice) {
                case 1:
                    System.out.println("Integer Sorting");
                    System.out.println("Do you want to input yourself or to generate it randomly ,press 1 for user input and 2 for random generate");
                    ch = sc.nextInt();
                    if (ch == 1) {

                        obj3.intarray();
                    } else {
                        obj2.intarray2();
                    }
                    break;
                case 2:
                    System.out.println("Character Sorting");
                    System.out.println("Do you want to input yourself or to generate it randomly ,press 1 for user input and 2 for random generate");
                    ch = sc.nextInt();
                    if (ch == 1) {
                        obj3.chararray();
                    } else {
                        obj2.chararray2();
                    }
                    break;
                case 3:
                    System.out.println("long Sorting");
                    System.out.println("Do you want to input yourself or to generate it randomly ,press 1 for user input and 2 for random generate");
                    ch = sc.nextInt();
                    if (ch == 1) {
                        obj3.longarray();
                    } else {
                        obj2.longarray2();
                    }
                    break;
                case 4:
                    System.out.println("boolean Sorting");
                    System.out.println("Do you want to input yourself or to generate it randomly ,press 1 for user input and 2 for random generate");
                    ch = sc.nextInt();
                    if (ch == 1) {
                        obj3.booleanarray();
                    } else {
                        obj2.booleanarray();
                    }
                    break;
                case 5:
                    System.out.println("String Sorting");
                    System.out.println("Do you want to input yourself or to generate it randomly ,press 1 for user input and 2 for random generate");
                    ch = sc.nextInt();
                    if (ch == 1) {
                        obj3.stringarray();
                    } else {
                        obj2.stringarray();
                    }
                    break;
                default:
                    System.out.println(" exiting...");
                    t = false;
                    break;

            }
        }
    }


}
