package com.company;



import java.util.concurrent.TimeUnit;// for waiting

public class Main  {

    public static void main(String[] args) {

        System.out.println("Hello this Program is for Bubble Sort in Java .");
        System.out.println("Here elements will be generated by users  .");
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("lets start");
        BubbleSort obj=new BubbleSort();
        obj.typesofArray();
    }



}
